language: rust
matrix:
 include:
   - rust: nightly
     env: FEATURES="--features rustc"
     before_script:
       rustup component add rustc-dev
   - rust: beta
     env: FEATURES=""
   - rust: stable
     env: FEATURES=""
   - rust: nightly
     env: FEATURES=""

script:
  - cargo test $FEATURES
  - cd test-project && cargo test $FEATURES

notifications:
  email:
    - pmunksgaard@gmail.com
    - laumann.thomas@gmail.com
